CC=g++
TARGET=a
FLAGS= -std=c++14 -static-libgcc 

16:
	$(CC) ${FLAGS} ./ex16/16.cpp ./ex16/breuk.cpp -o $(TARGET) && ./$(TARGET)

17:
	$(CC) ${FLAGS} ./ex17/17.cpp -o $(TARGET) && ./$(TARGET)

clean:
	rm $(TARGET)
