CC=g++
TARGET=a
FLAGS= -std=c++14 -static-libgcc 

11:
	$(CC) ${FLAGS} 11.cpp -o $(TARGET) && ./$(TARGET)

12:
	$(CC) ${FLAGS} 12.cpp -o $(TARGET) && ./$(TARGET)

13:
	$(CC) ${FLAGS} 13.cpp -o $(TARGET) && ./$(TARGET)


clean:
	rm $(TARGET)
