CC=g++
TARGET=a
FLAGS= -std=c++14 -static-libgcc 

11:
	$(CC) ${FLAGS} 11.cpp -o $(TARGET) && ./$(TARGET)

12:
	$(CC) ${FLAGS} 12.cpp containers.h -o $(TARGET) && ./$(TARGET)

13:
	$(CC) ${FLAGS} 13.cpp -o $(TARGET) && ./$(TARGET)

14:
	$(CC) ${FLAGS} 14.cpp -o $(TARGET) && ./$(TARGET)

15:
	$(CC) ${FLAGS} 15.cpp -o $(TARGET) && ./$(TARGET)

clean:
	rm $(TARGET)
