CC=g++
TARGET=a
FLAGS= -std=c++14 -static-libgcc 

1:
	$(CC) ${FLAGS} 1.cpp -o $(TARGET) && ./$(TARGET)

2:
	$(CC) ${FLAGS} 2.cpp -o $(TARGET) && ./$(TARGET)

3:
	$(CC) ${FLAGS} 3.cpp -o $(TARGET) && ./$(TARGET)

4:
	$(CC) ${FLAGS} 4.cpp -o $(TARGET) && ./$(TARGET)

5:
	$(CC) ${FLAGS} 5.cpp -o $(TARGET) && ./$(TARGET)

6:
	$(CC) ${FLAGS} 6.cpp -o $(TARGET) && ./$(TARGET)

7:
	$(CC) ${FLAGS} 7.cpp -o $(TARGET) && ./$(TARGET)

clean:
	rm $(TARGET)