CC=g++
TARGET=a
FLAGS= -std=c++14 -static-libgcc 

8:
	$(CC) ${FLAGS} 8.cpp -o $(TARGET) && ./$(TARGET)

9:
	$(CC) ${FLAGS} 9.cpp -o $(TARGET) && ./$(TARGET)

10:
	$(CC) ${FLAGS} 10.cpp -o $(TARGET) && ./$(TARGET)


clean:
	rm $(TARGET)