CC=gcc
TARGET=a

33:
	$(CC) 33.c -o $(TARGET) -lm && ./$(TARGET)

34:
	$(CC) 34.c -o $(TARGET) && ./$(TARGET)

35:
	$(CC) 35.c -o $(TARGET) && ./$(TARGET)

36:
	$(CC) 36.c -o $(TARGET) && ./$(TARGET)

37:
	$(CC) 37.c -o $(TARGET) && ./$(TARGET)

clean:
	rm $(TARGET)